name: 'ESLint Plus 2'
description: 'Runs ESLint against changed files with customization, issue commenting, and more'
author: 'Braden R. Napier & Zach Whitehead'
branding: 
  icon: 'code'
  color: 'red'
inputs:
  github-token:
    description: 'GitHub repository token for publishing inline lint annotations. Should be secrets.GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  reportWarnings:
    description: 'By setting this to "false", only errors will be annotated'
    required: false
  reportWarningsAsErrors:
    description: 'Report eslint warnings as errors? Defaults to false'
    required: false
  reportIgnoredFiles:
    description: 'Report any file paths which were ignored? Defaults to false'
    required: false
  reportSuggestions:
    description: 'Report suggestions with the rules? Defaults to true'
    required: false
  issueSummary:
    description: 'Should the bot provide a summary of the results as a comment? Defaults to true'
    required: false
  issueSummaryType:
    description: 'Changes the PR comment to be "full" (as shown on actions page) or "compact", defaults to compact'
    required: false
  issueSummaryMethod:
    description: 'When issueSummary is enabled, allows having the bot edit or refresh the comment on each new push'
    required: false
  issueSummaryOnlyOnEvent:
    description: 'Should an issue comment only occur when there are warnings or errors?'
    required: false
  extensions:
    description: 'Optionally provide a comma-separated list of extensions (checks js, jsx, ts, tsx by default)'
    required: false
  includeGlob:
    description: 'Optionally provide a glob to include. Will include all if not provided'
    required: false
  ignoreGlob:
    description: 'Optionally provide ignore pattern to use.  Will also use eslintignore unless specified'
    required: false
  configFile:
    description: 'A config file to use, defaults to the default config file at process.cwd()'
    required: false
  rulePaths:
    description: 'Optional comma-separated list of rule paths to use'
    required: false
  errorOnUnmatchedPattern:
    description: 'Throw error if unmatched pattern is seen?  Defaults to false'
    required: false
  useEslintrc:
    description: 'Use eslintrc?  Defaults to true'
    required: false
  useEslintIgnore:
    description: 'Set to false to not use eslintignore. Defaults to true'
    required: false
  fix:
    description: 'Run with --fix? Defaults to false'
    required: false
  npmInstall:
    description: 'Force run npm ci (or yarn) for you. If you do not use this option, be sure to install the project dependencies before running this action.  By default it will run if a node_modules directory is not found or this is set to true'
    required: false
    default: 'false'
runs:
  using: docker
  image: Dockerfile
  args:
    - "${{ inputs.github-token }}"
    - "${{ inputs.npmInstall }}"
